[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12", features = ["json", "blocking"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1"
serde = { version = "1.0", features = ["derive"] }
shared ={ path = "../shared" }
shared_c2_client ={ path = "../shared_c2_client" }
chrono = { version = "0.4.41", features = ["serde"] }
dotenvy = "0.15.7"
iced = { version = "0.13.1", features = ["tokio"] }
rfd = { version = "0.15.4", default-features = false, features = ["tokio", "gtk3"] }
