services: 
  app:
    container_name: "client"
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 4040:4040
    environment:
      # This must match the token on the C2!
      - ADMIN_TOKEN=fdgiyh%^l!udjfh78364LU7&%df!!