[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = {version = "1.0", features = ["derive"] }
serde_json = "1"
sqlx = { version = "=0.8.6", features = ["postgres", "chrono"] }
chrono = { version = "0.4.41", features = ["serde"] }